### ISSUE TITLE
Issue with calc example

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#1]
Exploring ngrest readme (my env Ubuntu )
- seems to be some character case issues
- the calc example fails to build after adding the add functionality
- doesn't automatically update as suggested it should.
[out.gz](https://github.com/loentar/ngrest/files/176184/out.gz)

**Comment by loentar** [comment]
Thank you for this issue report. If you have multiple issues please submit each as separate issue.

The build is now fixed. Please upgrade ngrest and start it again from calculator example directory.

```
ngrest upgrade
cd /path/to/calculator
ngrest
```


What do you mean under "some character case issues" and "doesn't automatically update"?

**Comment by loentar** [comment]
The other issues should be fixed in 30e4f003da1af8df27273b82bf69229b4daf8720
