### ISSUE TITLE
build_package() issue in ngrest script

### ISSUE THREAD

**Issue by oldmammuth** [loentar/ngrest#19]
in commit b0d2ee2e8e414a695342ca808b72697868a49a32, dated Dec 12, 2016,

line 769 (numbering from [commit](https://github.com/loentar/ngrest/commit/b0d2ee2e8e414a695342ca808b72697868a49a32) )was deleted, which read as following
``` bash
MAKE=make
```
leaving line 752 (current numbering) with an unbound variable, MAKE: 
``` bash
$MAKE >make-build.log
```
To correct the issue, it would be sufficient to restore above line 752 the deleted line, or change ```$make``` into ```make```

I got good results with, because I was adding make flags
``` bash
make ${MAKE_FLAGS:-} >make.log || return $?
```
Sorry if I didn't make a pull request, but an issue is the fatest way right now, please feel free to delete it as pleased.
Have a good 2017!

**Comment by loentar** [comment]
Thanks, it should work now.
