### ISSUE TITLE
Syntax error on upgrade

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#2]
Thanks for the quick response. Upgrade was not successful, ending with syntax error. Services no longer start at all. Upgrade output below.

david@betty:~$ ngrest upgrade
Checking for upgrades...
Already on 'master'
remote: Counting objects: 19, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 19 (delta 11), reused 11 (delta 11), pack-reused 4
Unpacking objects: 100% (19/19), done.
From https://github.com/loentar/ngrest
   b6b5b08..30e4f00  master     -> origin/master
Configuring ngrest for the build...
Building ngrest. It may take few minutes...
Installing ngrest script into ~/bin/
Upgrade completed.
**/home/david/bin/ngrest: line 466: syntax error near unexpected token `)'

**Comment by loentar** [comment]
Yes, this was fixed in 30e4f003da1af8df27273b82bf69229b4daf8720 and now you have fixed version. Further upgrades should work well.
