### ISSUE TITLE
ngrest binary

### ISSUE THREAD

**Issue by jamesaxl** [loentar/ngrest#20]
when I built ngrest from source I really do not know where ngrest binary to create project, by the way I search in build/deploy/bin but nothing

**Comment by loentar** [comment]
How do you built it?

**Comment by jamesaxl** [comment]
cmake -DWITH_EXAMPLES=1 ../ngrest

**Comment by loentar** [comment]
Ah, You're looking for `ngrest` binary and cannot find it.. So it's not a binary. It's a shell script and located in `scripts` directory of source code.

**Comment by jamesaxl** [comment]
thanks a lot I get it
