### ISSUE TITLE
Please escape special characters in strings instead of writing them into a json output.

### ISSUE THREAD

**Issue by sulakm** [loentar/ngrest#22]
Like comma, newline and other ascii < 0x20.
Now they are just written to the output.

**Comment by sulakm** [comment]
file: core/json/src/JsonWriter.cpp
method: JsonWriterImpl::writeNode(const Node* node)
            case ValueType::String:
                pool->putChar('"');
                pool->putCString(**ESCAPE**(value->value));
                pool->putChar('"');
                break;

**Comment by loentar** [comment]
Agree, but comma doesn't need to be escaped. Only backslash, double quote and everything what has code less than 0x20.

**Comment by sulakm** [comment]
I am sorry, I meant quote, not comma.
