### ISSUE TITLE
Memory leak in client context handling

### ISSUE THREAD

**Issue by dlichtenberger** [loentar/ngrest#24]
Environment: Linux 4.9, GCC 6.3.1

Hammering the "hello world" echo service [1] I noticed memory usage increasing quickly (e.g. 10000 identical requests --> memory usage goes up from 4M to 190M). Valgrind points to ClientHandler::connected as the source for the leak.

The leak seems to be triggered by ::recv returning -1 right before the client closes the connection. 

This is literally the first contact I had with ngrest, so I don't know if this fix is valid, but modifying this part at the end of ClientHandler::processResponse to set processing to false fixes the leak for me (but might of course break something else):

```c++    
    if (res == Status::Done && closeConnection) {
        NGREST_ASSERT_NULL(closeCallback);
        LogDebug() << "Closing connection to client";
        clientContext->processing = false;
        closeCallback->closeConnection(clientContext->fd);
    }
```

[1] e.g. with ab2 from apache2-utils:
`ab2 -n 10000 -c 10 "http://localhost:9098/helloworld/echo"`

**Comment by loentar** [comment]
Probably introduced in 37de177867ca49204dc93c39c9a61c4d2ccffefc..
