### ISSUE TITLE
Can't deploy

### ISSUE THREAD

**Issue by BryanDollery** [loentar/ngrest#27]
Remote deployment is failing with:

  'cp: cannot stat '.ngrest/local/build/deploy/*': No such file or directory'

I'm using the command

  `ngrest deploy user@myserver`

Where myserver is an ip-address.

The deploy-server command worked absolutely fine and remotely deployed the ngrest server to my remote machine, and it runs with no problems. The error occurs when I try to deploy my app.

I'm running inside a docker container, which seems to work fine for local development. Standing up a local server works fine and I can successfully invoke my REST methods and get a good response, and, like I said, deploy-server works ok too. So, the installation of ngrest (in docker) seems to be ok. I've installed ngrest in a docker container running ubuntu:trusty and I'm running ngrest from within a bash shell from within that. I rebuilt the image this morning, and the image builds ngrest from source, so I have the latest version of ngrest (and the latest stable version of docker too).

Any help would be appreciated, thanks.

Update: I've just read the bash-script code and it seems I need to make a bundle before doing a deploy. I've just tried that and I get exactly the same error message (though bundle-server works ok). I've also tried creating the directory it's complaining about, and chmodding it to 777, without any success.

**Comment by loentar** [comment]
Have you build it first like that?

`ngrest build`

Or just `ngrest`, then Ctrl+C

for me `ngrest build && ngrest deploy user@server` works fine.

**Comment by BryanDollery** [comment]
Brilliant! That's it, thanks very much it worked like a dream.
