### ISSUE TITLE
Post json data?

### ISSUE THREAD

**Issue by BryanDollery** [loentar/ngrest#28]
I'm trying to write a service that responds to:

  curl --data '{"yype":"zzz", "event":"yyy", "mkt":"xxx", "sel":"www"}' -X POST -H "Content-Type: application/json" http://localhost:9098/myservice/myop

I've created a struct in a header file called MyThing and a method:
    // *method: POST
    // *location: /myop/{thing}
  void myservice::myop(const MyThing& thing);

I don't know if this is the right approach, so any advice would be welcome. 

When I compile I get an error message generated from MyServiceWrapper.cpp:52 undefined reference to 'MyThingSerializer::deserialize(ngrest::Node const *, MyThing&)

btw: loving the library so far, thank you.

**Comment by loentar** [comment]
Guess you declared `MyThing` in separate header file. In this case you should add it manually into inner CMakeLists.txt

change this line:

`set(MYSERVICE_HEADERS myservice.h)`

to this:

`set(MYSERVICE_HEADERS myservice.h mystructs.h)`

where `mystructs.h` is the file containing `MyThing`.


Also i'm not sure if codegen understand if you declare `void myservice::myop(const MyThing& thing);` in header file (including class name).
And `*method:` or `*location:` has no effect in cpp file.

**Comment by loentar** [comment]
Also, I'm afraid it's not currently possible to unwind the parameters exactly as you write. Every parameter must be a child of the request object:

so, for the service like that

```
// *location: myservice
class myservice: public ngrest::Service
{
public:
    // *method: POST
    void myop(const MyThing& thing);
};
```

the curl request should be like that:
`curl --data '{"thing":{"yype":"zzz", "event":"yyy", "mkt":"xxx", "sel":"www"}}' -X POST -H "Content-Type: application/json" http://localhost:9098/myservice/myop`



One more note.. if you bind the operation location like that

`// *location: /myop/{thing}`

ngrest will try to read `thing` from both URL and POST body.. 

Better is to do not include data into URL this way.. Just remove this line or remove the bound argument.


-----

but this should be OK if you do it like this:

```
    // *method: PUT
    // *location: /myop/{id}
    void myop(int id, const MyThing& thing);
```

place id into URL and data into body.

**Comment by BryanDollery** [comment]
Thanks for the rapid response, it helped a lot. I declared the header in the cmakelists file, changed the json data structure, and the removed the argument binding in the URL. After these simple changes it just worked. This really is pleasant to work with.
