### ISSUE TITLE
Callback namespace in Wrapper.cpp codegen

### ISSUE THREAD

**Issue by klepsydra-robotics** [loentar/ngrest#29]
Hi ,

I think that line 100 of the [Wrapper.cpp](https://github.com/loentar/ngrest/blob/master/tools/ngrestcg/templates/service/Wrapper.cpp) should read:
`::ngrest::Callback< $($callbackType) >`

Instead of: 
`Callback< $($callbackType) >`

Otherwise, you need to use the ngrest namespace in your code. Like it happened in my case.

Thanks,

Pablo.

**Comment by loentar** [comment]
You're right. Fixed. Thank you..
