### ISSUE TITLE
Check for inotifywait failing

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#3]
I found I had to change the check for inotifywait in ngrest in order to get it working. It was aborting on the check ...

 #inotifywait -h >/dev/null 2>&1
    which inotifywait >/dev/null 2>&1
    #if [ $? -eq 127 ] # command not found
    if [ $? -eq 1 ] # command not found

**Comment by loentar** [comment]
This should not help because `set -eu` will break script execution on the first error.
`which` will return 1 and script will stop.

**Comment by loentar** [comment]
Fixed, please upgrade.
