### ISSUE TITLE
only callback as method param

### ISSUE THREAD

**Issue by klepsydra-robotics** [loentar/ngrest#30]
Hi,

I found another thing that might be an issue, but I am not 100% sure. In the file [serviceRequest.cpp](https://github.com/loentar/ngrest/blob/master/tools/ngrestcg/templates/common/serviceRequest.cpp) the line no. 9 states that if there is only one param, and it is MessageContext, we don't expect a param from the URL, and we don't need the asserts, but that's not the case for Callbacks,. I have a method with only one callback as param, I do get the asserts which prevent my method to be invoked.

Therefore, I think that if we have a callback method with no params, then the method should also fall into the case of the MessageContext, That's why I have change this line locally to this:

`##ifneq($(operation.params.$count)-$(operation.params.param.dataType.name),1-Callback||1-MessageContext)`

Please let me know if this is correct, or if there is an alternative way to achieve the same behavior.

Thanks,

Pablo.

**Comment by loentar** [comment]
Yes, you're right again. This is correct solution. Thanks.
