### ISSUE TITLE
Questions from a newbie

### ISSUE THREAD

**Issue by iot-cloud** [loentar/ngrest#34]
Hi Loentar,

Can I create multiple resources in a project.

users, groups, roles etc

thus in turn deploy multiple services to a project.

Thanks and Regards, Henry

**Comment by loentar** [comment]
Please see my answer here:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ngrest/ecfYAqplCdk/F9wioTGzBAAJ
