### ISSUE TITLE
Deploying service to server

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#4]
What is required to deploy a new version to a production web server? I don't want to push all the source & build scripts to the server.

**Comment by loentar** [comment]
Sure, will write wiki for this ASAP.

**Comment by loentar** [comment]
I think actual deployment to the server may be managed via scripts. Something like `ngrest deploy user@server[:/path/to/ngrest-build]` which uses ssh to connect and deploy current project. Also this will require to develop server-side script to manage service files updates and re-load the service on the fly without restarting the server itself. But this will need some effort... 
What do you think?


For now, if you don't have/don't want to have your sources and ngrest sources on your production server (which is good idea of course), you must have build environment on your desktop which is binary compatible with your production server - ideally the same version of OS (for example `Ubuntu 14.04 LTS server` on your server and `Ubuntu 14.04 LTS` on desktop).
If your desktop OS is not binary compatible with the server, you may need to setup chroot environment on your desktop (or server).

To setup ngrest to the server you need to copy `~/.ngrest/ngrest-build/deploy` directory from your desktop to some location on your server, for example to `/opt/ngrest`. It's good idea to remove any development-related files like headers and codegen. 

After you install the ngrest server binaries to your server you can deploy your service. To do that copy contents of directory `.ngrest/local/build/services` to `$NGREST_ROOT/share/ngrest/services` e.g. `/opt/ngrest/share/ngrest/services`.

After that you can start ngrest server like that:

```
cd /opt/ngrest/bin
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/../lib ./ngrestserver -p <SERVER_PORT>
```

Also you can manage logging via `NGREST_LOG_*` environment variables, please see `ngrest help run` and sources of Log.cpp for details.

To simplify this I will now add a command to create ngrest server bundle from `ngrest` script.

**Comment by loentar** [comment]
Please update and try new command:

`ngrest bundle-server`

This will create server bundle.


Your services still needs to be copied into `/opt/ngrest/services` manually.

**Comment by loentar** [comment]
d393072 added three new commands to deploy the server, create project bundle and deploy project to remote host.

How to use:

https://github.com/loentar/ngrest/wiki/Deploying-ngrest-to-remote-host

Next time I will add commands to start and stop remote ngrest server.
