### ISSUE TITLE
Newbie question - changes not showing

### ISSUE THREAD

**Issue by magick93** [loentar/ngrest#42]
Hi

I'm making changes to the sample echo service - simple things like returning the contents of the return string, also changing rest service description.

But my changes never show!

I compile.
I have tried `ngrest run`, `ngrest clean`, `ngrest build`, `make`, sacrificing goats... nothing is working!

When I make syntax errors it doesnt compile. When I am not in the right directory `ngrest` complains. It seems like, when in the right directory, and running ngrest, it pulls a service from somewhere else.

Any ideas as to what I might be doing wrong?

**Comment by loentar** [comment]
Please use Google Groups or Gitter to ask questions.

https://github.com/loentar/ngrest#support


Are you sure you call the correct service? Try to see the list of the services in ngrest service tester and make sure it's the right service.
