### ISSUE TITLE
when i after create a new project, and want to run it.  it report error:

### ISSUE THREAD

**Issue by cpusoft** [loentar/ngrest#44]
when i after create a new project, and want to run it.  it report error:

$cd echo/
$ngrest
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

how solve it ? thx alot

**Comment by loentar** [comment]
You have very old version of git, please upgrade it.
