### ISSUE TITLE
May u be able to extend the rest api to cover ajax as well

### ISSUE THREAD

**Issue by iot-cloud** [loentar/ngrest#45]
Hi ngrest gatekeeper

When you are programming using the web interface, rest and ajax are supported.

Is there a possibility to extend the current ngrest to support ajax as well.

What does it take to extend the current ngrest to support ajax? Any pointer is much appreciate?

Thanks and Regards.

**Comment by loentar** [comment]
I don't understand your question. ngrest is designed to do AJAX. You have to request web resource and get result as JSON (or other format).

**Comment by iot-cloud** [comment]
Hi Dimtry,

I have tried to use AJAX from ExtJS to NGREST before.

NGREST does not seem throw an exception in regarding the incorrect Context-Type.

Let me work on an example to capture the error and will let you know ASAP.

Regards, Henry

**Comment by loentar** [comment]
As I remember there was a problem with ExtJS.
If you pass wrong Content-Type to ngrest it will respond with `Can't handle content type: xxxx`
