### ISSUE TITLE
Error after adding ngrest-db to the project 

### ISSUE THREAD

**Issue by khairy-mohamed** [loentar/ngrest#47]
after adding ngrest-db on MACOS 
ld: library not found for -lngrestdbpostgres
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [deploy/share/ngrest/services/conf.dylib] Error 1
make[1]: *** [conf/CMakeFiles/conf.dir/all] Error 2
make: *** [all] Error 2

**Comment by loentar** [comment]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/ngrest/uD0ScSUbJvQ

this should resolve the error, replace `libsqlite3` to `postgres`.
