### ISSUE TITLE
Return JSON from a service

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#5]
The service currently returns the the single json element {"Result":"Hello"}. I would like to return a more complex son element. How might that be accomplished? For example:
{
	"pets": [{
		"species": "canine",
		"name": "spot",
		"birthdate": "Jan 1, 2010"
	}, {
		"species": "feline",
		"name": "puff",
		"birthdate": "July 4, 2014"
	}]
}

**Comment by loentar** [comment]
I think we need documentation for that and forum for questions...

The forum will be: https://groups.google.com/forum/#!forum/ngrest

--

**Please upgrade ngrest before starting this example.** Had few typos in codegeneration templates :)

To make service response with complex data type you can define struct and work with it as usual. If you need to return array you can use either of `std::list` or `std::vector`. Also `std::map` supported to pass key-value objects.

Here is an example on how to implement response like yours:

**Pets.h**
```
#ifndef PETS_H
#define PETS_H

#include <ngrest/common/Service.h>
#include <string>
#include <list>

struct Pet
{
    enum class Species
    {
        canine,
        feline
    };

    Species species;
    std::string name;
    std::string birthday;
};

//! Pets service
/*! Example of using complex data types */
// *location: pets
class Pets: public ngrest::Service
{
public:
    //! gets list of pets
    std::list<Pet> getPets();
};

#endif // PETS_H
```

**Pets.cpp**

```

#include "Pets.h"

std::list<Pet> Pets::getPets()
{
    return std::list<Pet>({
        {
            Pet::Species::canine,
            "spot",
            "Jan 1, 2010"
        },
        {
            Pet::Species::feline,
            "puff",
            "July 4, 2014"
        },
    });
}

```

After you start the service under ngrest and follow http://localhost:9098/pets/getPets , you can see this response:

![image](https://cloud.githubusercontent.com/assets/4038431/13913601/6ecbef0a-ef59-11e5-9d8b-13b1aa7a29cb.png)

**Comment by dgschoenmaker** [comment]
Nice! (and simple) I really like this and appreciate your quick response! Thanks.
