### ISSUE TITLE
Configure ngrest on VM

### ISSUE THREAD

**Issue by hoang408** [loentar/ngrest#55]
Could anyone show me how to configure ngrest to run in VM Ubuntu 18.04 (VM running on Windows 7)?

I can ping the Ubuntu 18.04 VM, which has been configured to Bridged Adapter from Virtual Box.  The sample site (info.php) can be accessed in the browser using `IP_address/info.php`.

It would be nice if the guide include such a section.  Thanks.

**Comment by loentar** [comment]
Please try to follow this guide: https://github.com/loentar/ngrest/wiki/Creating-and-starting-a-project-guide-with-screenshots

Just replace `localhost` with your VM's IP when you access it outside of VM like: http://YOUR_VM_IP:9098/ngrest/services

Make sure firewall doesn't block ngrest port (9098 by default).

Also, please see complete wiki section: https://github.com/loentar/ngrest/wiki
