### ISSUE TITLE
Service returning invalid JSON

### ISSUE THREAD

**Issue by rubiot** [loentar/ngrest#58]
When a webservice returns a response larger than 64K it sometimes responds with an invalid JSON. The JSON always breaks a little after byte 65536 (65550, 65543, etc.). Considering this is the size of the response chunk, this indicates an error on the chunks reassembling. I'm using it on Apache.

**Comment by rubiot** [comment]
Here is an instance of the problem (the asterisk marks byte 65535). Two field names in a row, the second one missing the initial quote. "logonTime" and "authenticatedBy" are field names, but there are several other fields in between them.
```
            *                    
"logonTime":authenticatedBy":"value"
```

**Comment by loentar** [comment]
Merged
