### ISSUE TITLE
Fails after upgrading ...

### ISSUE THREAD

**Issue by dgschoenmaker** [loentar/ngrest#6]
After upgrade, ngrest no longer works ...
david@debian:~$ cd myproject
david@debian:~/myproject$ ls
CMakeLists.txt  myproject
david@debian:~/myproject$ ngrest
Package  is not installed locally. Installing...
fatal: could not create work tree dir ''.: No such file or directory

**Comment by loentar** [comment]
Fixed, please upgrade again
