### ISSUE TITLE
Debug in IDE

### ISSUE THREAD

**Issue by HenryQW** [loentar/ngrest#66]
Hi @loentar,

I'm relatively new to c++, can you provide the steps on how to debug a project created by ngrest? Preferably in VS Code or Qt Creator.

Thanks!

**Comment by loentar** [comment]
1. Open your project in QtCreator, selecting CMakeLists.txt.
2. Select Debug config.
3. Build it.
4. Select projects -> Build, Copy Build Directory
5. Select Run, Set

Executable: 

Command line arguments: `-s <COPIED_DIR>/deploy/share/ngrest/services`


6. Set breakpoints, Run project
