### ISSUE TITLE
How to install from the source?

### ISSUE THREAD

**Issue by mouse07410** [loentar/ngrest#69]
I've cloned this repo, and with CMake built the stuff. It created subdirectory `build/deploy/` with two binaries `ngrestcg` and `ngrestserver`, shared libraries, etc.

Attempt to follow the Wiki guide resulted in
```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/opt/local -DWITH_EXAMPLES=1 ..
Skipping Nginx module compilation: no Nginx source path provided
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_EXAMPLES


-- Build files have been written to: /Users/ur20980/src/ngrest/build
```

`make test`, `make check`, `make install` do not exist.

Attempt to `./run_cppcheck` results in
```
. . . . .
^

^
nofile:0:0: information: Cppcheck cannot find all the include files (use --check-config for details) [missingInclude]
```

Is there a script or such to install the result the right way?

**Comment by loentar** [comment]
Please see Wiki section:

https://github.com/loentar/ngrest/wiki/Build-ngrest-from-source-code

**Comment by loentar** [comment]
Or.. it's much simpler to install it like this: https://github.com/loentar/ngrest/wiki/Installation-guide-with-screenshots

**Comment by mouse07410** [comment]
> Please see Wiki section:
>
> https://github.com/loentar/ngrest/wiki/Build-ngrest-from-source-code

This tells how to **build** from the source, but not how to **install** or use the result (except for mentioning how to start the server).

> Or.. it's much simpler to install it like this: https://github.com/loentar/ngrest/wiki/Installation-guide-with-screenshots

Except that I explicitly need to build **from the source**. And it's unclear what gets pulled by the script used above.

And, of course, none of the above answers the question of how to test the installation.

**Comment by loentar** [comment]
I've added `test` and `install` targets. Please see the [updated guide](https://github.com/loentar/ngrest/wiki/Build-ngrest-from-source-code).

Because of you build the code manually it doesn't contain the `ngrest` script, so you have to [create your project, set up, build and run everything manually](https://github.com/loentar/ngrest/wiki/Create-and-run-a-service-manually)
