### ISSUE TITLE
feature: adding ip address to listen to as param

### ISSUE THREAD

**Issue by yya** [loentar/ngrest#7]
Hi Dmitry,

great job!  how can one tell the server to listen to a specific ip address.
for port one may use NGREST_SERVER_PORT=XXXX
is there any option for ip address like NGREST_SERVER_IP=0.0.0.0

thnx
yupp

**Comment by loentar** [comment]
Now there is an option you mentioned. IPv4 and IPv6 addresses are supported.

Please upgrade with `ngrest upgrade`.

How to use:
```
NGREST_SERVER_IP=192.168.0.12 ngrest
NGREST_SERVER_IP=::1 ngrest
```

**Comment by yya** [comment]
thanks a lot. it works as expected.
