### ISSUE TITLE
Can we use ngrest like this?

### ISSUE THREAD

**Issue by audnex** [loentar/ngrest#73]
Linux Embedded Arm processor (i.Mx6).With embedded web server (Nginx) running as local web server. 

We want to add REST API function to our existing C and C++ code that runs on our processor so that the API can set and get the current status of parameters.

Is this supported? 

From your doc I'm confused by how ngrest works through Nginx and how we get and set status with c++ or c program.

Help appreciated!

**Comment by loentar** [comment]
You have to wrap your code to the service and deploy it to nginx. Depending on your code logic you may need IPC because nginx may start the multiple instances (processes and threads) of the service.

**Comment by audnex** [comment]
ok thanks.
