### ISSUE TITLE
Modify return string from {"result":"text"} to text or {text} or ...

### ISSUE THREAD

**Issue by MG-Sika** [loentar/ngrest#76]
Is it possible to modify the API-Response from the static format {"result":"text"} to a different format?

I prefer to return only a string that have to be formatted by the callback.

**Comment by loentar** [comment]
Try using `inlineResult` like this:

```
// *inlineResult: true
std::string echo(const std::string& text);
```

**Comment by MG-Sika** [comment]
Thanks. It solves my problem.
