### ISSUE TITLE
support for HTTP PATCH

### ISSUE THREAD

**Issue by raadiy** [loentar/ngrest#78]
Hi,  Firstly, thank you for developing NGREST. It is a useful solution. I find that HTTP PATCH method is not supported by NGREST. I need to use PATCH for accomplishing few tasks. Could you please provide support for it, and if possible let us know about when it would be available.

Regards
Raajesh

**Comment by loentar** [comment]
Done, please see CRUD example for details:

https://github.com/loentar/ngrest/blob/master/examples/crud/src/Crud.h
https://github.com/loentar/ngrest/blob/master/examples/crud/src/Crud.cpp

**Comment by raadiy** [comment]
Thank you very much. Will try this. Regards, Raajesh
