### ISSUE TITLE
Fails to build because switches aren't spaced

### ISSUE THREAD

**Issue by Spaghetti-Cat** [loentar/ngrest#8]
On my Archlinux 64-bit system when I run your installation script this is my output:
```
[I][~/programs/ngrest-build]$ ./inst.sh                                                                                      
Cloning into 'ngrest'...
remote: Counting objects: 1747, done.
remote: Total 1747 (delta 0), reused 0 (delta 0), pack-reused 1747
Receiving objects: 100% (1747/1747), 748.00 KiB | 687.00 KiB/s, done.
Resolving deltas: 100% (1034/1034), done.
Checking connectivity... done.
Configuring ngrest for the build...
Skipping Nginx module compilation: no Nginx source path provided
Building ngrest. It may take few minutes...
cc: error: unrecognized command line option ‘-fstack-protector-strong-I/usr/include/httpd’; did you mean ‘-fstack-protector-strong’?
make[2]: *** [modules/apache2/CMakeFiles/ngrest_apache2_mod.dir/build.make:63: modules/apache2/CMakeFiles/ngrest_apache2_mod.dir/src/mod_ngrest.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:826: modules/apache2/CMakeFiles/ngrest_apache2_mod.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

The cause of this error is line 6 of file `modules/apache2/CMakeFiles/ngrest_apache2_mod.dir/flags.make` in the build directory:

`C_FLAGS = -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong-I/usr/include/httpd -I. -I/usr/include/apr-1 -I/usr/include  -fPIC`

As you can see, there should be a space between the switches.

Workaround is to add this line:
```
sed -i 's/g-I/g -I/I' "modules/apache2/CMakeFiles/ngrest_apache2_mod.dir/flags.make"
```
in the installation script after the line:
```
echo "Building ngrest. It may take few minutes..."
```

**Comment by loentar** [comment]
Thank you for submitting this issue. Unfortunately I can't check it on ArchLinux right now.

Can you post output of these two lines?

`apxs -q CFLAGS EXTRA_INCLUDES`

`apxs -q LDFLAGS`

**Comment by Spaghetti-Cat** [comment]
`apxs -q CFLAGS EXTRA_INCLUDES` produces:
```
-march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong;;-I/usr/include/httpd -I. -I/usr/include/apr-1 -I/usr/include
```
`apxs -q LDFLAGS` produces:
```
-Wl,-O1,--sort-common,--as-needed,-z,relro
```

PS: Many thanks for the project! :) I like how easy it is to get running.

**Comment by loentar** [comment]
Please try to install it again. The bug should be fixed now. If not, please reopen the issue.

**Comment by Spaghetti-Cat** [comment]
I tried it and now it works! Great, thank you :)
