### ISSUE TITLE
Microsoft.CppCommon.targets(209,5): error MSB6006: "cmd.exe" exited with code 1

### ISSUE THREAD

**Issue by Annirudh-sh** [loentar/ngrest#82]
this error keeps coming during the compilation of Linphone desktop application on windows.

![log2](https://user-images.githubusercontent.com/61970861/152940689-c11b6e24-c71d-4118-a270-b7fa5441c71a.png)

**Comment by loentar** [comment]
This is not a Linphone issue tracker, sorry.
