### ISSUE TITLE
deploying NGREST filter in Apache

### ISSUE THREAD

**Issue by raadiy** [loentar/ngrest#84]
Hi Dmitry,

I would like to deploy NGREST services that I developed on Apache. I also have a filter used by the services that needs to be deployed. So far, I have been using the test HTTP server that you have included in NGREST. I have seen your procedure for deploying services, but how to deploy the filter. Kindly help.

Regards
Raajesh

**Comment by loentar** [comment]
Hi, the similar way like services: you have to setup `FiltersPath` to the path. I updated the wiki
```
  # optional path to deploy ngrest filters from, if not set, no filters get deployed
  FiltersPath /home/user/.ngrest/ngrest-build/deploy/share/ngrest/filters
```

**Comment by raadiy** [comment]
Thank you Dmitry, I will try it.
