### ISSUE TITLE
This OS is not supported yet

### ISSUE THREAD

**Issue by Allov** [loentar/ngrest#9]
Followed instructions for Windows installation and getting this error when executing the bash script: `This OS is not support yet.`

Running `uname -s` gives me `MSYS_NT-6.1` but the scripts wants `MINGW`. I'm not sure if it's because I installed MinGW the wrong way or if my OS (Windows 7 64bits) is really unsupported.

Here's the full log:

```
--2016-09-20 14:38:15--  http://bit.ly/ngrest
Resolving bit.ly (bit.ly)... 67.199.248.10, 67.199.248.11
Connecting to bit.ly (bit.ly)|67.199.248.10|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/loentar/ngrest/master/scripts/inst [
following]
--2016-09-20 14:38:16--  https://raw.githubusercontent.com/loentar/ngrest/master
/scripts/inst
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.20.13
3
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.20.1
33|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3554 (3.5K) [text/plain]
Saving to: 'STDOUT'

-                   100%[=====================>]   3.47K  --.-KB/s   in 0.008s

2016-09-20 14:38:16 (431 KB/s) - written to stdout [3554/3554]

This OS is not yet supported
```

**Comment by loentar** [comment]
I didn't checked it under Win7 x64. Will check and answer you asap.

**Comment by loentar** [comment]
Can you please say which installer of MinGW you used?

Also, please provide the value of PATH environment variable within bash:

```
echo "$PATH"
```

**Comment by Allov** [comment]
Here goes:

```
echo $PATH

/c/Python27/:/c/Python27/Scripts:/c/Program Files (x86)/Common Files/Rockwell:/c/ProgramData/Oracle/Java/javapath:/c/windows/system32:/c/windows:/c/windows/System32/Wbem:/c/windows/System32/WindowsPowerShell/v1.0/:/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit/:/c/Program Files/Microsoft SQL Server/110/Tools/Binn/:/c/Program Files/Perforce/DVCS/:/c/Program Files (x86)/Microsoft SDKs/TypeScript/1.0/:/c/Program Files/Microsoft SQL Server/120/Tools/Binn/:/c/Program Files (x86)/Xoreax/IncrediBuild:/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/c/Program Files/TortoiseSVN/bin:/c/ProgramData/chocolatey/bin:/c/Program Files/Git/cmd:/c/Program Files/Git/mingw64/bin:/c/Program Files/Git/usr/bin:/c/Program Files (x86)/Common Files/Rockwell/:/c/Program Files (x86)/Rockwell Software/RSCommon:/c/tools/python:/c/Program Files (x86)/Rockwell Automation/Common/Components:/c/Program Files/VisualSVN Server/bin:/c/Program Files/nodejs/:/c/windows/system32/config/systemprofile/.dnx/bin:/c/Program Files/Microsoft DNX/Dnvm/:/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/c/Program Files/dotnet/:/c/Program Files (x86)/Microsoft SQL Server/90/Tools/binn/:/c/Program Files/CMake/bin:/c/windows/system32/config/systemprofile/Application Data/ngrest/bin:/mingw/bin:/usr/bin:"C:/Program Files (x86)/Microsoft VS Code":/c/work/batch-utils:"C:/Program Files/Sublime Text 3":/c/Program Files (x86)/Microsoft VS Code/bin:/c/tools/python/Scripts:/c/Users/f.charest/AppData/Roaming/npm
```

As for MinGW it was `mingw-get 0.6.2`, `gcc 5.3.0` and `bash 3.1`.

**Comment by loentar** [comment]
You have Git Paths before MinGW paths and because of that, GIT's mingw64 dir is used to start `uname.exe`.

![image](https://cloud.githubusercontent.com/assets/4038431/18713134/ea8bd12c-8019-11e6-9621-42e199adceb9.png)

Expected is:

![image](https://cloud.githubusercontent.com/assets/4038431/18713262/50e761ca-801a-11e6-8db6-5f7042b95207.png)

Git paths must be *after MinGW*.


When testing I discovered another bug.. Looks like bash 3.1 is too old to start `ngrest` script. Will try to do something with it.

**Comment by Allov** [comment]
Ok, it worked! But, `ngrest create` command does indeed crash: `ngrest: line 39: declare: -A: invalid option`. Perhaps this is the same bug you were talking about?

**Comment by loentar** [comment]
yes.. this is the that bug. I didn't find a method on how to install bash4 with MSYS.. For now I just disable extensions support under windows.

**Comment by loentar** [comment]
I think I have fixed it. Also [installation guide](https://github.com/loentar/ngrest/wiki/Installation-guide-with-screenshots-Windows) is slightly changed.
Please try to install ngrest again.

**Comment by Allov** [comment]
Alright, it's working now! Is there a way to run the server self-contained? In other words, can I instantiate it  from code instead of running the command line?

**Comment by Allov** [comment]
Humm, actually, after looking how it works, I think this won't be possible due to the service generation.

**Comment by loentar** [comment]
Actually, it's possible but need some effort to complete.

You must change project type to executable by changing `add_library` to `add_executable` in `CMakeLists.txt`.

Next, add to your project sources from server excluding server's main.cpp, something like that:

```
set(NGREST_SOURCE_DIR "$ENV{HOME}/.ngrest/ngrest")

include_directories("${NGREST_SOURCE_DIR}/core/server/src/")

FILE(GLOB YOURTARGET_SOURCES ${PROJECT_SOURCE_DIR}/*.cpp ${NGREST_SOURCE_DIR}}/core/server/src/*.cpp)

list(REMOVE_ITEM YOURTARGET_SOURCES ${NGREST_SOURCE_DIR}/core/server/src/main.cpp)
```

replace `YOURTARGET` to your target name, e.g. `CALC`. 


Next you can create your own server, here is an example on how to do that:
https://github.com/loentar/ngrest/blob/master/tests/deployment/src/main.cpp

**Comment by loentar** [comment]
[Here](https://github.com/loentar/ngrest/files/489242/calc-standalone.zip) is the working example on how to create standalone server.

Unpack and build from shadow directory:

```
unzip calc-standalone.zip
mkdir calc-standalone-build
cmake ../calc-standalone
make
```

Start the standalone server:

```
deploy/bin/calc
```

Please note, there will be only your service(s): no services tester nor favicon services.


Test it in web browser: [http://localhost:8080/calc/echo?text=test](http://localhost:8080/calc/echo?text=test)

**Comment by edras** [comment]
First of all, you did a very good job with ngrest. Congratulations!
I followed your instructions under Ubuntu and Win7, both 64bits, and it worked very nice.

But I tried to compile your standalone example on win7 64 and it didn't work. The problem was on the definition of the sighandler_t, which I think is only available on Linux. So I wrote this function to replace the sighandler_t:

`void signalHandler (int sig) {
    ngrest::LogInfo() << "Stopping server";
    server.quit();
}`

But I still get problems with undefined reference after linking:

> [ 16%] Linking CXX executable ..\deploy\bin\calc.exe  CMakeFiles\calc.dir/objects.a(main.cpp.obj):main.cpp:(.text+0x7a): undefined reference to `ngrest::Server::quit()'

Do you have any clue about it? 

Another question: Is it possible to control the state of the simple http server of ngrest? 
I tried to deploy the calc service on Apache / Windows but I faced many problems with the apxs module and I guess it is not possible to deploy it under windows.

**Comment by loentar** [comment]
You're right regarding sighandler_t. I used Linux-only version for the example. Will fix it asap.

Please insert these lines after includes to get it compiled under Windows and MacOSX (leaving signalHandler as from example):

```
#if defined WIN32 || defined __APPLE__
typedef void(__cdecl *sighandler_t)(int);
#endif
```

Here is full working example of main.cpp - as it defined in the ngrest simple http server: https://github.com/loentar/ngrest/blob/master/core/server/src/main.cpp


What do you mean under "contol the state of the simple ngrest http server"?

I didn't tried to build and deploy Apache2 module under Windows, will try and fix it asap.

**Comment by loentar** [comment]
@edras, can you please provide link to Apache2 installer for Windows you used?

**Comment by edras** [comment]
I think there is something missing in the make files. I am getting undefined references either at Ubuntu as well at Windows

Ubuntu: 

> [ 16%] Building CXX object calc/CMakeFiles/calc.dir/src/main.cpp.o
[ 33%] Linking CXX executable ../deploy/bin/calc
CMakeFiles/calc.dir/src/main.cpp.o: na função `main::{lambda(int)#1}::operator()(int) const':
main.cpp:(.text+0x10c): undefined reference `ngrest::Server::quit()'
CMakeFiles/calc.dir/src/main.cpp.o: na função `main':
main.cpp:(.text+0x328): undefined reference `ngrest::Server::Server()'
main.cpp:(.text+0x341): undefined reference `ngrest::Server::~Server()'
main.cpp:(.text+0x3b6): undefined reference `ngrest::ClientHandler::ClientHandler(ngrest::Engine&, ngrest::Transport&)'
main.cpp:(.text+0x3ca): undefined reference `ngrest::Server::setClientCallback(ngrest::ClientCallback*)'
main.cpp:(.text+0x3de): undefined reference `ngrest::Server::create(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'
main.cpp:(.text+0x5f2): undefined reference `ngrest::Server::exec()'
main.cpp:(.text+0x60f): undefined reference `ngrest::ClientHandler::~ClientHandler()'
main.cpp:(.text+0x718): undefined reference `ngrest::ClientHandler::~ClientHandler()'
collect2: error: ld returned 1 exit status
calc/CMakeFiles/calc.dir/build.make:185: recipe for target 'deploy/bin/calc' failed
make[2]: *** [deploy/bin/calc] Error 1
CMakeFiles/Makefile2:85: recipe for target 'calc/CMakeFiles/calc.dir/all' failed
make[1]: *** [calc/CMakeFiles/calc.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Windows:

> [ 12%] Building CXX object calc/CMakeFiles/calc.dir/src/ClientHandler.cpp.obj
[ 25%] Linking CXX executable ..\deploy\bin\calc.exe
CMakeFiles\calc.dir/objects.a(ClientHandler.cpp.obj):ClientHandler.cpp:(.text+0x286): undefined reference to `__imp_getnameinfo'
CMakeFiles\calc.dir/objects.a(ClientHandler.cpp.obj):ClientHandler.cpp:(.text+0x36f): undefined reference to `gai_strerrorA'
CMakeFiles\calc.dir/objects.a(ClientHandler.cpp.obj):ClientHandler.cpp:(.text+0xa65): undefined reference to `__imp_recv'
CMakeFiles\calc.dir/objects.a(ClientHandler.cpp.obj):ClientHandler.cpp:(.text$_ZN6ngrest11writeChunksEyRxRNS_17MessageWriteStateE[_ZN6ngrest11writeChunksEyRxRNS_17MessageWriteStateE]+0x75):
undefined reference to `__imp_send'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x362): undefined reference to `__imp_listen'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x8f4): undefined reference to `__imp_select'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xa21): undefined reference to `__WSAFDIsSet'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xa9e): undefined reference to `__WSAFDIsSet'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xd5e): undefined reference to `__imp_getaddrinfo'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xd80): undefined reference to `gai_strerrorA'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xe41): undefined reference to `__imp_socket'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xe8b): undefined reference to `__imp_setsockopt'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xeb9): undefined reference to `__imp_bind'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0xf22): undefined reference to `__imp_freeaddrinfo'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x1153): undefined reference to `__imp_ioctlsocket'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x1169): undefined reference to `__imp_WSAGetLastError'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x127c): undefined reference to `__imp_accept'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x13c3): undefined reference to `__imp_setsockopt'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text+0x1518): undefined reference to `__imp_ioctlsocket'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text$_ZN6ngrest17SocketInitializerC1Ev[_ZN6ngrest17SocketInitializerC1Ev]+0x27): undefined reference to `__imp_WSAStartup'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text$_ZN6ngrest17SocketInitializerC1Ev[_ZN6ngrest17SocketInitializerC1Ev]+0x43): undefined reference to `__imp_WSAGetLastError'
CMakeFiles\calc.dir/objects.a(Server.cpp.obj):Server.cpp:(.text$_ZN6ngrest17SocketInitializerD1Ev[_ZN6ngrest17SocketInitializerD1Ev]+0xf): undefined reference to `__imp_WSACleanup'
collect2.exe: error: ld returned 1 exit status
calc\CMakeFiles\calc.dir\build.make:244: recipe for target 'deploy/bin/calc.exe' failed
mingw32-make[2]: *** [deploy/bin/calc.exe] Error 1
CMakeFiles\Makefile2:84: recipe for target 'calc/CMakeFiles/calc.dir/all' failed
mingw32-make[1]: *** [calc/CMakeFiles/calc.dir/all] Error 2
Makefile:82: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Regarding your question, under Windows, I used the binaries from  [Apache Haus](https://www.apachehaus.com/cgi-bin/download.plx) version 2.4.23 x64

Before landing on your project, I was trying to develop a CGI application for IIS. I have a DLL that handles the functionality of a proprietary hardware and I want to expose some functions of this DLL in REST. Afterwards, I will consume the REST service with jQUERY. I never developed Web applications in C++ before, it was always JAVA, Linux, Apache and PHP.

I think ngrest, as is, would fulfill my requirements. The question is (1) how to start the ngrest server without building every time the source code, (2) redirect the output to a log file, (3) put ngrest as a service, and (4) start/stop the service. Could you explain the first question to me? The following questions I will do my homework.

**Comment by loentar** [comment]
Regarding error under Linux, it's like it cannot find ngrest server source files. Please make sure you have `~/.ngrest/ngrest/core/server/src` directory and files there as follows:

`ClientCallback.h  ClientHandler.cpp  ClientHandler.h  main.cpp	servercommon.h	Server.cpp  Server.h  strutils.h``

If you don't see that files please make symlink to reproduce the directory structure or adjust it's path in `calc-standalone/calc/CMakeLists.txt`:

```
set(NGREST_SOURCE_DIR "$ENV{HOME}/.ngrest/ngrest")
```

replace with real path

---

Regarding windows build error.. Sometimes CMake fails to detect ws2_32 dep, and you need to add it explicitly into `calc-standalone/calc/CMakeLists.txt` lines as follows:

```
    target_link_libraries(calc ws2_32)
```

---

Apache Haus is built with MSVC14.. Guess it's incompatible with MinGW build... Well.. I will try to make working ngrest working with VC14 .

---

1) ngrest server is not building every time you run ngrest script. That script only starts `cmake`, `make` and then `ngrestserver` with special arguments.

To build your project without using ngrest script:

```
# first create project with ngrest script
ngrest create Echo
# next build it manually
mkdir echo-build && cd echo-build
cmake ../echo
make
```

now your service is built. To start it under ngrest server start within the same directory:

```
~/.ngrest/ngrest-build/deploy/bin/ngrestserver -s $PWD/deploy/share/ngrest/services
```

---
2) To control log use `NGREST_LOG_FILE`, `NGREST_LOG_FILE_APPEND`, `NGREST_LOG_LEVEL`, `NGREST_LOG_VERBOSITY`.


`NGREST_LOG_FILE` - redirect output to desired file
`NGREST_LOG_FILE_APPEND` if set to `1` or `TRUE` -- append to file instead of rewriting
`NGREST_LOG_LEVEL` set log level to one of values:
  - ALERT 
  - CRIT
  - ERROR
  - WARNING
  - NOTICE
  - INFO
  - DEBUG
  - VERBOSE
  - TRACE

`NGREST_LOG_VERBOSITY` -- control fields output: can be conjunction of: 
  - TEXT
  - LEVEL
  - FILELINE
  - FUNCTION
  - DATETIME
  - DEFAULT
  - ALL


---

3, 4) I'm not familiar with how to create windows services. If you have any ideas, please say.

Under Linux - you can create simple init.d script or just put ngrest startup command into `/etc/rc.local`

**Comment by edras** [comment]
Thank you! Now it works under Linux and Windows.

By Windows, at `calc-standalone/calc/CMakeLists.txt`, Instead of

`target_link_libraries(calc ngrestutils ngrestcommon ngrestjson ngrestengine $ENV{NGREST_EXT_LIBS})`

Following your instructions, I inserted ws2_32:

`target_link_libraries(calc ws2_32 ngrestutils ngrestcommon ngrestjson ngrestengine $ENV{NGREST_EXT_LIBS})`

Now it compiles without errors. ;)

Your instructions on how to start the ngrest server also worked and I will use it to develop the windows service. Actually it has no priority right now, but I will share here when it is done.

Regarding Apache VC14, I will use it to handle sessions using the Mod_Rewrite and forward to the ngrest server in a different port. So, there is no need to integrate ngrest  with Apache under Windows.

Thank you for your help!

**Comment by edras** [comment]
Reading this [Simple Windows Service](http://www.codeproject.com/Articles/499465/Simple-Windows-Service-in-Cplusplus) I was able to successfully deploy the ngrestserver as a windows service.

We need to include the windows header and the following variables:
```
#include <windows.h>
#include <tchar.h>

SERVICE_STATUS        g_ServiceStatus = {0};
SERVICE_STATUS_HANDLE g_StatusHandle = NULL;
char serviceName[] = "NGRest Server";
ngrest::Server server;
```
With g_ServiceStatus, we tell windows the state of the service (Starting, Started, Stopped).
g_StatusHandle is a handle from where windows keeps reference to the service.

For a windows service to work properly, we need to define 3 functions:
```
VOID WINAPI ServiceMain (DWORD argc, LPTSTR *argv);
VOID WINAPI ServiceCtrlHandler (DWORD);
DWORD WINAPI ServiceWorkerThread (LPVOID lpParam);
```
ServiceMain initializes the handles, attach g_StatusHandle to the ServiceCtrlHandler and deploys the Thread which will execute the ngrestserver.

ServiceCtrlHandler will be called by windows to stop or restart the service. 

The main function is as follows:
```
int _tmain (int argc, TCHAR *argv[])
{

    SERVICE_TABLE_ENTRY ServiceTable[] =
    {
        {serviceName, (LPSERVICE_MAIN_FUNCTION) ServiceMain},
        {NULL, NULL}
    };

    if (StartServiceCtrlDispatcher (ServiceTable) == FALSE)
    {
        return GetLastError ();
    }

    return 0;
}
```
The service table will pass to windows the service name and the ServiceMain reference.
My ServiceMain looks like this:
```
VOID WINAPI ServiceMain (DWORD argc, LPTSTR *argv)
{
	OutputDebugString(_T("NGRest Server: ServiceMain: Entry"));

    // Register our service control handler with the SCM
    g_StatusHandle = RegisterServiceCtrlHandler (serviceName, ServiceCtrlHandler);

    if (g_StatusHandle == NULL)
    {
        return;
    }

    // Tell the service controller we are starting
    ZeroMemory (&g_ServiceStatus, sizeof (g_ServiceStatus));
    g_ServiceStatus.dwServiceType = SERVICE_WIN32_OWN_PROCESS;
    g_ServiceStatus.dwControlsAccepted = 0;
    g_ServiceStatus.dwCurrentState = SERVICE_START_PENDING;
    g_ServiceStatus.dwWin32ExitCode = 0;
    g_ServiceStatus.dwServiceSpecificExitCode = 0;
    g_ServiceStatus.dwCheckPoint = 0;

    if (SetServiceStatus (g_StatusHandle , &g_ServiceStatus) == FALSE)
    {
        OutputDebugString(_T(
          "NGRest Server: ServiceMain: SetServiceStatus returned error"));
    }

    /*
     * Perform tasks necessary to start the service here
     */

	// Tell the service controller we are started
	g_ServiceStatus.dwControlsAccepted = SERVICE_ACCEPT_STOP;
	g_ServiceStatus.dwCurrentState = SERVICE_RUNNING;
	g_ServiceStatus.dwWin32ExitCode = 0;
	g_ServiceStatus.dwCheckPoint = 0;

	if (SetServiceStatus (g_StatusHandle, &g_ServiceStatus) == FALSE)
	{
		OutputDebugString(_T(
		  "NGRest Server: ServiceMain: SetServiceStatus returned error"));
	}

	OutputDebugString(_T("NGRest Server: ServiceMain: starting server"));

    // Start a thread that will perform the main task of the service
    HANDLE hThread = CreateThread (NULL, 0, ServiceWorkerThread, NULL, 0, NULL);

    // Wait until our worker thread exits signaling that the service needs to stop
    WaitForSingleObject (hThread, INFINITE);

    OutputDebugString(_T("NGRest Server: ServiceMain: thread terminated"));

    /*
     * Perform any cleanup tasks
     */

    // Tell the service controller we are stopped
    g_ServiceStatus.dwControlsAccepted = 0;
    g_ServiceStatus.dwCurrentState = SERVICE_STOPPED;
    g_ServiceStatus.dwWin32ExitCode = 0;
    g_ServiceStatus.dwCheckPoint = 3;

    if (SetServiceStatus (g_StatusHandle, &g_ServiceStatus) == FALSE)
    {
        OutputDebugString(_T(
          "NGRest Server: ServiceMain: SetServiceStatus returned error"));
    }
    OutputDebugString(_T("NGRest Server: ServiceMain: Exit"));

    return;
} 
```
CreateThread, creates a new Thread which will execute the ngrestserver, returning a handle to that thread. The ServiceMain will then call WaitForSingleObject (hThread, INFINITE) and wait up the main Thread is finished or stopped by the ServiceCtrlHandler.

The ServiceCtrlHandler looks like this:
```
VOID WINAPI ServiceCtrlHandler (DWORD CtrlCode)
{
    switch (CtrlCode)
	{
    	case SERVICE_CONTROL_STOP :

        if (g_ServiceStatus.dwCurrentState != SERVICE_RUNNING)
           break;

        /*
         * Perform tasks necessary to stop the service here
         */

        g_ServiceStatus.dwControlsAccepted = 0;
        g_ServiceStatus.dwCurrentState = SERVICE_STOP_PENDING;
        g_ServiceStatus.dwWin32ExitCode = 0;
        g_ServiceStatus.dwCheckPoint = 4;

        if (SetServiceStatus (g_StatusHandle, &g_ServiceStatus) == FALSE)
        {
            OutputDebugString(_T(
              "NGRest Server: ServiceCtrlHandler: SetServiceStatus returned error"));
        }

        // This will signal the worker thread to start shutting down
        server.quit();
        break;

    	default:

        break;
    }
}
```
To stop the thread, I called server.quit().

Finally, the WorkerThread looks like this:
```
DWORD WINAPI ServiceWorkerThread (LPVOID lpParam)
{
    ngrest::StringMap args;

    ngrest::ServiceDispatcher dispatcher;
    ngrest::Deployment deployment(dispatcher);
    ngrest::HttpTransport transport;
    ngrest::Engine engine(dispatcher);
    ngrest::ClientHandler clientHandler(engine, transport);

    server.setClientCallback(&clientHandler);

    if (!server.create(args))
        return ERROR_SUCCESS;

    const std::string& servicesPath = std::string(std::getenv("NGREST_HOME")) +
    		std::string("\\ngrest-build\\deploy\\share\\ngrest\\services\\");

    deployment.deployAll(servicesPath);

    deployment.deployAll(std::string(std::getenv("SERVICES_HOME"))
    		+NGREST_PATH_SEPARATOR);

    server.exec();

    return ERROR_SUCCESS;
}
```
The only difference from your example, is that I created an environment variable called "SERVICES_HOME" to point to the location of the services created by ngrest.

After compilation and generation of the .EXE file, I installed the service by typing as administrator:

> sc create "NGRest Server" binPath= PATH_TO_THE_EXE_FILE

It is important to note that there is a space mark between "binPath=" and PATH_TO...
If you change the EXE file, it is not necessary to reinstall the service. Just replace the EXE and restart the service by the windows service window.

Now, to start the service, open the windows service window under ControlPanel->Administrative Tools-> Services, find the "NGRest Server", right click over it and start the service. If it doesn't start, right click over the service, select properties -> Logon, and change the account of the service from Local System to a user account, type the account name and password. Now it should work.

**Comment by loentar** [comment]
Good work!

Can create simple wiki-page on how to create and manage own ngrest server as Windows service and attach source archive there?

Something like that: https://github.com/loentar/ngrest/wiki/Standalone-HTTP-server

**Comment by loentar** [comment]
Also I think, for the services it's better to store `SERVICES_HOME` somewhere in Windows registry instead of environment. 
For example: HCLM\Software\ngrest\servicesHome="....."


And these lines of code needs to be removed:

```
    const std::string& servicesPath = std::string(std::getenv("NGREST_HOME")) +
            std::string("\\ngrest-build\\deploy\\share\\ngrest\\services\\");

    deployment.deployAll(servicesPath);
```

**Comment by edras** [comment]
Ok, no problem. The wiki "Windows-Service-HTTP-server" would be under this address?

>  https://github.com/loentar/ngrest/wiki/Windows-Service-HTTP-server

I never wrote a wiki before... But I will try. And yes, I think it is better to work with the Windows Registry. 

I wrote those lines with "NGREST_HOME" because `ngrest::Runtime::getSharePath()` was not getting the right path to the serviceSatus and favicon services.

**Comment by loentar** [comment]
Yes, it should map to that path. Anyway after you create new Wiki page it will appear to the right panel.

Guess `getSharePath` doesn't work because of when server is started as windows service application exe name is `svchost.exe`?

**Comment by edras** [comment]
I don't know. 
`ngrest::Runtime::getSharePath()` returns `C:\share\ngrest`
`ngrest::Runtime::getApplicationRootPath()` returns `C:`

using:

```
char result[ MAX_PATH ];
std::string tmp = std::string( result, GetModuleFileName( NULL, result, MAX_PATH ) );
```
It returns the path location of .EXE file.

**Comment by loentar** [comment]
That's really strange, I'm getting the exe name with the same way:
https://github.com/loentar/ngrest/blob/master/core/utils/src/Runtime.cpp#L76

And the check for the path is non-empty is present at the end of function.. Since you don't have exception on startup the path should be valid...

and my version works for me:
W/08-11-2016 18:03:53.466 C:\Users\user\Documents\devel\ngrest\core\server\src\main.cpp:95 main: C:\Users\user\Documents\devel\ngrest-build\deploy\share\ngrest\services\

**Comment by edras** [comment]
I understand now what is going on. My .EXE containing the ngrest server integrated with windows service is not placed at the same path as the ngrestserver compiled under the ngrest project. My EXE was placed at 
C:\ServerTest\.  This is why it does not find the correct path to the favicon e statusserver services...
