### ISSUE TITLE
What is the right use (or main differences) of ngrest / ngrestserver ?

### ISSUE THREAD

**Issue by JL2014** [loentar/ngrest#92]
Hi,

Most documentation indicates using "ngrest" command.

What is the good way to have the ngrest command ? copy "scripts/ngrest" to "/usr/local/bin" ?

Is "ngrest" only for "development" and we must use "ngrestserver" in "production" ?

Greetings, JL.

**Comment by loentar** [comment]
The `ngrest` command is available when you installed ngrest using installed like mentioned in https://github.com/loentar/ngrest#install .

It just simplifies things a bit.

**Comment by JL2014** [comment]
Hi @loentar,

if I understand you correctly, the "automatic install" do the job to install the "ngrest" command in the path and then automatically available from prompt but a "manual" install from "make install" command don't install the "ngrest" command ?

Greetings, JL.

**Comment by loentar** [comment]
`ngrest` command is a bash script which installed with `inst` script. If you do cmake build `ngrest` script isn't going to be installed.
