### ISSUE TITLE
Skipping Nginx module compilation: no Nginx source path provided

### ISSUE THREAD

**Issue by JL2014** [loentar/ngrest#93]
Hi,

How to avoid the warning "Skipping Nginx module compilation: no Nginx source path provided" when use cmake ?
At first sight, I can ignore it when not in "production" ?
Is there a "development" define ?

cmake -DNGINX_PATH=.... "." ?
( as I can see in https://github.com/loentar/ngrest/wiki/Deploy-ngrest-under-Nginx )

If yes, could you confirm it is root Nginx path ? Nginx header path ? Nginx binary path ? other path ?

Greetings, JL.

**Comment by loentar** [comment]
Like mentioned it should be current directory after a set of commands:

```
mkdir ~/nginx-build && cd ~/nginx-build
cd nginx-*
NGINX_PATH=$PWD make -C ~/.ngrest/ngrest-build
```

so it would be `~/nginx-build/nginx-[NGINX_VERSION]`

**Comment by JL2014** [comment]
Hi @loentar,

Ok, i know this folder is used "only" for Nginx sources, I think documentation would indicate "nginx-sources" instead of "nginx-build".

Greetings, JL.

**Comment by JL2014** [comment]
Hi @loentar,

Ok, i know this folder is used "only" for Nginx sources, I think documentation would indicate "nginx-sources" instead of "nginx-build".

Greetings, JL.
