### ISSUE TITLE
number of nested levels in request json

### ISSUE THREAD

**Issue by raadiy** [loentar/ngrest#95]
Hi Dmitry,

 I am using MessageContext as the only argument in the service to parse and use the incoming json (content type is application/json, it is a HTTP POST service handler).
 Before reaching the service, does the ngrest platform do any parsing on the incoming message, even if the service expects only the message context?
 If there is any such parsing of request json, can it be turned off, so that the service just receives the json and parses it only once.
 Is there any restriction on the number of nested levels in the request json. Kindly let me know.
 
 Regards
 Raajesh

**Comment by loentar** [comment]
Hi, well, it gets processed by the filters. also parsed with JSON parser. By intention MessageContext should have request->node as parsed JSON object.

you may look into Engine for details
```
void Engine::dispatchMessage(MessageContext* context)
```

**Comment by raadiy** [comment]
Thank you
