### ISSUE TITLE
ngrest module does not come up with nginx server due to "module is not binary compatible" error

### ISSUE THREAD

**Issue by raadiy** [loentar/ngrest#97]
Hi Dmitry,

 I have built nginx ( version nginx-1.22.1 ) downloaded from http://nginx.org/en/download.html for a specific requirement.
 I then built the ngrest module for nginx. However, when I try to bring nginx up, I get the following error, and nginx does not come up.
 
 nginx: [emerg] module "/temp/raajesh/test/nginx/modules/mod_ngrest.so" is not binary compatible in /temp/raajesh/test3/nginx/conf/nginx.conf:1
 
 
 Is there a specific version of nginx that I should be using ? 
 
 Please let me know

Regards
Raajesh

**Comment by loentar** [comment]
Hi, you should rebuild ngrest nginx module like described here: https://github.com/loentar/ngrest/wiki/Deploy-ngrest-under-Nginx#obtain-nginx-source-code

Use your path to nginx sources instead

**Comment by raadiy** [comment]
thank you
